### ISSUE TITLE
[LAS/LAZ vaults:] The load of table should not be case sensitive.

### ISSUE THREAD

**Issue by romulogoncalves** [MonetDB/data-vaults#12]
goncalve@budapest:Tests$ mclient debug sql < load.sql 
MAPI  = monetdb@localhost:55001
QUERY = call lidarload('C_14FN1');
ERROR = !Could not find table C_14FN1.
goncalve@budapest:Tests$ mclient debug sql
Welcome to mclient, the MonetDB/SQL interactive terminal (unreleased)
Database: MonetDB v11.24.0 (unreleased), 'test'
Type \q to quit, \? for a list of available commands
auto commit mode: on
sql>select count(*) from C_14FN1;
% sys.L1 # table_name
% L1 # name
% wrd # type
% 1 # length
[ 0	]
sql>

**Comment by kutsurak** [comment]
Fixed.
