### ISSUE TITLE
[LAS/LAZ vaults]: Use decimal instead of double.

### ISSUE THREAD

**Issue by romulogoncalves** [MonetDB/data-vaults#7]
The coordinates X, Y and Z should be loaded into decimals.
The scale can be retrieved from the file header and the number of digits is possible to calculated using the min and max value. Currently decimal(8,2) is enough to store AHN2 and AHN3 data sets.

**Comment by kutsurak** [comment]
Done. The precision and the scale of each data column when a file is attached, and creates SQL columns with the appropriate decimal type. Then, when loading, it reads the data deciding at run time what should be the type of the underlying BAT that we need to create. 

(This is probably the weirdest piece of C code I've written so far)
